export const restaurants = [
  {
    id: 'century-burger',
    name: 'Century Burger',
    nameAr: 'سنتري برجر',
    menu: [
      {
        category: 'New Items',
        categoryAr: 'الجديد',
        items: [
          {
            name: 'Philly Hot Dog',
            nameAr: 'هوت دوج فيلي',
            description: 'Freshly baked hot dog bun, oven-grilled hot dog with special marination, grilled vegetables, mozzarella cheese, sweet pickle and special cocktail sauce',
            descriptionAr: 'خبز هوت دوج طازج، هوت دوج مشوي بتتبيلة خاصة، خضروات مشوية، جبن موزاريلا، مخلل حلو وصوص كوكتيل خاص',
            price: '31.00 SR',
          },
          {
            name: 'Brisket Burger',
            nameAr: 'برجر البريسكيت',
            description: 'CB beef patty stacked with 8-hour smoked brisket, smoky BBQ sauce, melted cheese, caramelized onions, and rich cheddar cheese',
            descriptionAr: 'باتي لحم بقري مع بريسكيت مدخن لـ8 ساعات، صوص باربيكيو مدخن، جبن مذاب، بصل مكرمل وجبن شيدر',
            price: '49.00 SR',
          },
        ],
      },
      {
        category: 'Classic Burgers',
        categoryAr: 'برجر كلاسيكي',
        items: [
          {
            name: 'The Original CB',
            nameAr: 'السي بي الأصلي',
            description: 'Thick CB beef patty, Swiss cheese, lettuce, tomato, onion, signature CB sauce, signature CB bun',
            descriptionAr: 'باتي لحم بقري سميكة، جبن سويسري، خس، طماطم، بصل، صوص سي بي المميز، خبز سي بي المميز',
            price: '39.00 SR',
          },
          {
            name: 'Beef Burger',
            nameAr: 'برجر لحم',
            description: 'Classic CB beef patty burger',
            descriptionAr: 'برجر باتي لحم بقري كلاسيكي',
            price: '34.00 SR',
          },
          {
            name: 'Grilled Chicken',
            nameAr: 'دجاج مشوي',
            description: 'Grilled chicken burger',
            descriptionAr: 'برجر دجاج مشوي',
            price: '32.00 SR',
          },
          {
            name: 'Fried Chicken',
            nameAr: 'دجاج مقلي',
            description: 'Crispy fried chicken burger',
            descriptionAr: 'برجر دجاج مقلي مقرمش',
            price: '33.00 SR',
          },
        ],
      },
      {
        category: 'Special Burgers',
        categoryAr: 'برجر خاص',
        items: [
          {
            name: 'Richy Truffle',
            nameAr: 'ريتشي تروفل',
            description: 'Premium truffle burger — 842 cal',
            descriptionAr: 'برجر تروفل فاخر — 842 سعرة حرارية',
            price: '42.00 SR',
          },
          {
            name: 'Coleslaw Sriracha',
            nameAr: 'كول سلو سريراتشا',
            description: 'Burger with coleslaw and sriracha sauce — 1113 cal',
            descriptionAr: 'برجر بالكول سلو وصوص سريراتشا — 1113 سعرة حرارية',
            price: '39.00 SR',
          },
          {
            name: 'Five Cheese',
            nameAr: 'خمسة أجبان',
            description: 'Five-cheese loaded burger — 615 cal',
            descriptionAr: 'برجر بخمسة أنواع من الجبن — 615 سعرة حرارية',
            price: '44.00 SR',
          },
          {
            name: 'Spicy Red',
            nameAr: 'الأحمر الحار',
            description: 'Spicy red burger — 968 cal',
            descriptionAr: 'برجر أحمر حار — 968 سعرة حرارية',
            price: '42.00 SR',
          },
          {
            name: 'Black Umami',
            nameAr: 'أومامي الأسود',
            description: 'Black bun umami burger — 750 cal',
            descriptionAr: 'برجر أومامي بخبز أسود — 750 سعرة حرارية',
            price: '41.00 SR',
          },
          {
            name: 'Bacon BBQ',
            nameAr: 'بيكون باربيكيو',
            description: 'Bacon and BBQ sauce burger — 975 cal',
            descriptionAr: 'برجر بيكون وصوص باربيكيو — 975 سعرة حرارية',
            price: '44.00 SR',
          },
          {
            name: 'Mushroom Melt',
            nameAr: 'مشروم ميلت',
            description: 'Mushroom and melted cheese burger — 975 cal',
            descriptionAr: 'برجر مشروم وجبن مذاب — 975 سعرة حرارية',
            price: '46.00 SR',
          },
        ],
      },
      {
        category: 'Diet Burgers',
        categoryAr: 'برجر دايت',
        items: [
          {
            name: 'Keto Burger',
            nameAr: 'برجر كيتو',
            description: 'Low-carb keto-friendly burger — 806 cal',
            descriptionAr: 'برجر منخفض الكربوهيدرات مناسب للكيتو — 806 سعرة حرارية',
            price: '39.00 SR',
          },
          {
            name: 'Lettuce Wrap Burger',
            nameAr: 'برجر لفافة الخس',
            description: 'Burger wrapped in lettuce instead of a bun — 758 cal',
            descriptionAr: 'برجر ملفوف بالخس بدلاً من الخبز — 758 سعرة حرارية',
            price: '37.00 SR',
          },
        ],
      },
      {
        category: 'Starters',
        categoryAr: 'مقبلات',
        items: [
          {
            name: 'Ranch Cheese Sticks',
            nameAr: 'عيدان الجبن بالرانش',
            description: 'Crispy cheese sticks with ranch dipping sauce',
            descriptionAr: 'عيدان جبن مقرمشة مع صوص الرانش',
            price: '27.00 SR',
          },
          {
            name: 'Boneless BBQ Wings',
            nameAr: 'أجنحة باربيكيو بلا عظم',
            description: 'Boneless chicken wings in BBQ sauce — 749 cal',
            descriptionAr: 'أجنحة دجاج بلا عظم بصوص الباربيكيو — 749 سعرة حرارية',
            price: '29.00 SR',
          },
          {
            name: 'Boneless Buffalo Wings',
            nameAr: 'أجنحة بافالو بلا عظم',
            description: 'Boneless chicken wings in buffalo sauce — 631 cal',
            descriptionAr: 'أجنحة دجاج بلا عظم بصوص البافالو — 631 سعرة حرارية',
            price: '29.00 SR',
          },
          {
            name: 'Crispy Chicken Strips',
            nameAr: 'أصابع الدجاج المقرمشة',
            description: 'Golden crispy chicken strips — 792 cal',
            descriptionAr: 'أصابع دجاج ذهبية مقرمشة — 792 سعرة حرارية',
            price: '28.00 SR',
          },
          {
            name: 'Sweet Buffalo Wings',
            nameAr: 'أجنحة بافالو الحلوة',
            description: 'Sweet and spicy buffalo wings — 743 cal',
            descriptionAr: 'أجنحة بافالو حلوة وحارة — 743 سعرة حرارية',
            price: '33.00 SR',
          },
          {
            name: 'Bang Bang Shrimp',
            nameAr: 'روبيان بانج بانج',
            description: 'Crispy shrimp with bang bang sauce — 1181 cal',
            descriptionAr: 'روبيان مقرمش بصوص بانج بانج — 1181 سعرة حرارية',
            price: '38.00 SR',
          },
          {
            name: 'Maple Sriracha Shrimp',
            nameAr: 'روبيان مابل سريراتشا',
            description: 'Shrimp glazed with maple sriracha — 533 cal',
            descriptionAr: 'روبيان بصوص المابل والسريراتشا — 533 سعرة حرارية',
            price: '39.00 SR',
          },
          {
            name: 'Sloppy Style Fries',
            nameAr: 'بطاطس سلوبي ستايل',
            description: 'Loaded sloppy-style fries — 811 cal',
            descriptionAr: 'بطاطس مع إضافات سلوبي ستايل — 811 سعرة حرارية',
            price: '33.00 SR',
          },
          {
            name: 'Mix Style Fries',
            nameAr: 'بطاطس ميكس ستايل',
            description: 'Mixed loaded fries — 509 cal',
            descriptionAr: 'بطاطس مشكلة — 509 سعرة حرارية',
            price: '30.00 SR',
          },
          {
            name: 'Cheesy Style Fries',
            nameAr: 'بطاطس تشيزي ستايل',
            description: 'Famous since 2011 — fries, signature CB sauce, caramelized onion, bacon, melted cheese — 878 cal',
            descriptionAr: 'مشهورة منذ 2011 — بطاطس، صوص سي بي المميز، بصل مكرمل، بيكون، جبن مذاب — 878 سعرة حرارية',
            price: '31.00 SR',
          },
        ],
      },
      {
        category: 'Salads',
        categoryAr: 'سلطات',
        items: [
          {
            name: 'Bacon Caesar Salad',
            nameAr: 'سلطة سيزر بالبيكون',
            description: 'Classic Caesar salad with crispy bacon — 580 cal',
            descriptionAr: 'سلطة سيزر كلاسيكية مع بيكون مقرمش — 580 سعرة حرارية',
            price: '26.00 SR',
          },
          {
            name: 'Black Beetroot Salad',
            nameAr: 'سلطة البنجر الأسود',
            description: 'Fresh beetroot salad — 750 cal',
            descriptionAr: 'سلطة بنجر طازجة — 750 سعرة حرارية',
            price: '25.00 SR',
          },
        ],
      },
      {
        category: 'Fries',
        categoryAr: 'بطاطس',
        items: [
          {
            name: 'Classic Fries',
            nameAr: 'بطاطس كلاسيك',
            description: 'Golden classic fries — 319 cal',
            descriptionAr: 'بطاطس ذهبية كلاسيكية — 319 سعرة حرارية',
            price: '11.00 SR',
          },
          {
            name: 'Cajun Spicy Fries',
            nameAr: 'بطاطس كاجون الحارة',
            description: 'Fries with cajun spice blend — 341 cal',
            descriptionAr: 'بطاطس بتوابل الكاجون — 341 سعرة حرارية',
            price: '18.00 SR',
          },
          {
            name: 'Parmesan Truffle Fries',
            nameAr: 'بطاطس بارميزان تروفل',
            description: 'Fries with parmesan and truffle oil — 424 cal',
            descriptionAr: 'بطاطس بجبن البارميزان وزيت التروفل — 424 سعرة حرارية',
            price: '19.00 SR',
          },
          {
            name: 'Sweet Potato Fries',
            nameAr: 'بطاطا حلوة',
            description: 'Crispy sweet potato fries',
            descriptionAr: 'بطاطا حلوة مقرمشة',
            price: '19.00 SR',
          },
        ],
      },
      {
        category: 'Desserts',
        categoryAr: 'حلويات',
        items: [
          {
            name: 'Crispy Caramel Bun',
            nameAr: 'بان كراميل مقرمش',
            description: 'Warm crispy caramel bun dessert — 761 cal',
            descriptionAr: 'حلوى خبز كراميل دافئة ومقرمشة — 761 سعرة حرارية',
            price: '23.00 SR',
          },
          {
            name: 'Triple Chocolate',
            nameAr: 'شوكولاتة ثلاثية',
            description: 'Rich triple chocolate dessert — 564 cal',
            descriptionAr: 'حلوى شوكولاتة ثلاثية غنية — 564 سعرة حرارية',
            price: '26.00 SR',
          },
          {
            name: 'Kunafa Pistachio Bun',
            nameAr: 'بان كنافة بالفستق',
            description: 'Kunafa-style pistachio bun — 872 cal',
            descriptionAr: 'خبز على طريقة الكنافة بالفستق — 872 سعرة حرارية',
            price: '26.00 SR',
          },
        ],
      },
      {
        category: 'Drinks',
        categoryAr: 'مشروبات',
        items: [
          {
            name: 'Lemon Mint',
            nameAr: 'ليمون بالنعناع',
            description: 'Fresh lemon mint drink',
            descriptionAr: 'مشروب ليمون بالنعناع الطازج',
            price: '17.00 SR',
          },
          {
            name: 'Fuzzy Passion Fruit',
            nameAr: 'فاشن فروت فوار',
            description: 'Sparkling passion fruit drink',
            descriptionAr: 'مشروب فاشن فروت فوار',
            price: '19.00 SR',
          },
          {
            name: 'Fuzzy Mix Berry',
            nameAr: 'توت مشكل فوار',
            description: 'Sparkling mixed berry drink — 173 cal',
            descriptionAr: 'مشروب توت مشكل فوار — 173 سعرة حرارية',
            price: '19.00 SR',
          },
          {
            name: 'Fuzzy Watermelon',
            nameAr: 'بطيخ فوار',
            description: 'Sparkling watermelon drink — 203 cal',
            descriptionAr: 'مشروب بطيخ فوار — 203 سعرة حرارية',
            price: '17.00 SR',
          },
          {
            name: 'Peanut Butter Shake',
            nameAr: 'شيك زبدة الفول السوداني',
            description: 'Creamy peanut butter milkshake — 805 cal',
            descriptionAr: 'ميلك شيك كريمي بزبدة الفول السوداني — 805 سعرة حرارية',
            price: '20.00 SR',
          },
          {
            name: 'Milkshake',
            nameAr: 'ميلك شيك',
            description: 'Available in Strawberry, Chocolate, or Vanilla — 783 cal',
            descriptionAr: 'متوفر بنكهات الفراولة، الشوكولاتة، أو الفانيلا — 783 سعرة حرارية',
            price: '20.00 SR',
          },
          {
            name: 'Fresh Orange Juice',
            nameAr: 'عصير برتقال طازج',
            description: 'Freshly squeezed orange juice — 135 cal',
            descriptionAr: 'عصير برتقال طازج معصور — 135 سعرة حرارية',
            price: '18.00 SR',
          },
          {
            name: 'Water (Arwa 500ml)',
            nameAr: 'مياه أروى 500مل',
            description: 'Arwa mineral water',
            descriptionAr: 'مياه معدنية أروى',
            price: '4.00 SR',
          },
        ],
      },
    ],
  },
];
